"use client";

import React from "react";
import Link from "next/link";
import { motion } from "motion/react";
import {
  ArrowRight,
  ClipboardList,
  Bot,
  TrendingDown,
  Target,
  Trophy,
  FileBarChart,
  Globe,
  Zap,
  Leaf,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { ThemeToggle } from "@/components/layout/theme-toggle";
import { cn } from "@/lib/utils";

const features = [
  {
    title: "Track Digital Habits",
    description: "Easily log your daily streaming, gaming, cloud storage, and device usage with collapsible, touch-friendly inputs.",
    icon: ClipboardList,
    color: "text-emerald-500 bg-emerald-500/10",
  },
  {
    title: "AI Coach Insights",
    description: "Receive personalized, actionable recommendations generated by Gemini AI to optimize your carbon output.",
    icon: Bot,
    color: "text-blue-500 bg-blue-500/10",
  },
  {
    title: "Carbon Score Calculator",
    description: "Understand your impact in real-time with an elegant circular dashboard gauge grading your digital efficiency.",
    icon: Globe,
    color: "text-amber-500 bg-amber-500/10",
  },
  {
    title: "Daily Green Challenges",
    description: "Complete daily digital cleaning challenges to earn XP and level up your eco streak badges.",
    icon: Target,
    color: "text-purple-500 bg-purple-500/10",
  },
  {
    title: "Future Simulation",
    description: "Visualize the long-term environmental difference you can make using predictive trajectory model charts.",
    icon: TrendingDown,
    color: "text-rose-500 bg-rose-500/10",
  },
  {
    title: "Comprehensive Reports",
    description: "Access detailed historical tables of your emissions, analyze trends, and export records directly to PDF.",
    icon: FileBarChart,
    color: "text-cyan-500 bg-cyan-500/10",
  },
];

const steps = [
  {
    step: "01",
    title: "Log Your Activity",
    description: "Spend 2 minutes inputting your daily digital actions like email counts, gaming time, and streaming resolution.",
  },
  {
    step: "02",
    title: "Get Carbon Analytics",
    description: "Our calculation engine converts activities into kg CO₂ and computes your personal Digital Carbon Score.",
  },
  {
    step: "03",
    title: "Take Action & Earn XP",
    description: "Implement AI coach tips, complete challenges, and build streak points to unlock achievements.",
  },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col selection:bg-emerald-500/35 overflow-x-hidden">
      {/* Header / Navbar */}
      <header className="sticky top-0 z-50 w-full h-16 border-b border-border bg-background/65 backdrop-blur-md flex items-center justify-between px-6 md:px-12">
        <div className="flex items-center gap-3">
          <div className="h-9 w-9 rounded-xl bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center">
            <span className="text-xl">🌿</span>
          </div>
          <span className="text-lg font-bold bg-gradient-to-r from-emerald-500 via-emerald-400 to-teal-400 bg-clip-text text-transparent">
            EcoByte
          </span>
        </div>
        <div className="flex items-center gap-4">
          <ThemeToggle />
          <Link href="/login">
            <Button variant="ghost" className="text-sm font-medium cursor-pointer">
              Login
            </Button>
          </Link>
          <Link href="/signup">
            <Button className="bg-emerald-600 hover:bg-emerald-500 text-white font-semibold text-sm rounded-xl cursor-pointer">
              Get Started
            </Button>
          </Link>
        </div>
      </header>

      {/* Hero Section */}
      <section className="relative flex flex-col items-center justify-center text-center px-6 pt-24 pb-20 md:pt-36 md:pb-32 bg-zinc-950 text-white">
        {/* Ambient radial glows */}
        <div className="absolute top-1/4 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[350px] rounded-full bg-emerald-500/15 blur-[120px] pointer-events-none" />
        <div className="absolute bottom-10 left-1/3 w-[300px] h-[300px] rounded-full bg-blue-500/10 blur-[100px] pointer-events-none" />

        <div className="max-w-4xl z-10 space-y-6">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.5 }}
            className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 text-xs font-semibold uppercase tracking-wider mb-2"
          >
            <Leaf className="h-3.5 w-3.5" />
            Introducing digital sustainability
          </motion.div>
          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.1 }}
            className="text-4xl sm:text-6xl font-extrabold tracking-tight leading-none bg-gradient-to-b from-white via-zinc-100 to-zinc-400 bg-clip-text text-transparent"
          >
            Know Your <br />
            <span className="bg-gradient-to-r from-emerald-400 via-teal-300 to-emerald-300 bg-clip-text text-transparent">
              Digital Carbon Footprint
            </span>
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="text-zinc-400 text-base sm:text-xl max-w-2xl mx-auto font-medium"
          >
            Most calculators measure cars and meat. EcoByte tracks the invisible impact of your digital life—streaming, cloud gaming, AI prompts, and online storage.
          </motion.p>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.3 }}
            className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-4"
          >
            <Link href="/signup">
              <Button size="lg" className="w-full sm:w-auto bg-emerald-500 hover:bg-emerald-400 text-zinc-950 font-bold text-base px-8 py-6 rounded-2xl shadow-lg shadow-emerald-500/20 cursor-pointer">
                Start Tracking Free
                <ArrowRight className="ml-2 h-5 w-5" />
              </Button>
            </Link>
            <a href="#features">
              <Button size="lg" variant="outline" className="w-full sm:w-auto border-zinc-800 bg-zinc-900/40 hover:bg-zinc-800 text-zinc-300 text-base px-8 py-6 rounded-2xl cursor-pointer">
                Explore Features
              </Button>
            </a>
          </motion.div>
        </div>
      </section>

      {/* Features Grid */}
      <section id="features" className="py-20 md:py-28 px-6 md:px-12 max-w-7xl mx-auto w-full">
        <div className="text-center space-y-3 mb-16">
          <h2 className="text-3xl md:text-4xl font-extrabold tracking-tight">
            How EcoByte Helps You Improve
          </h2>
          <p className="text-muted-foreground max-w-lg mx-auto text-sm md:text-base">
            Track habits, challenge yourself, visualize your progress, and get actionable coaching tips.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feat, index) => {
            const Icon = feat.icon;
            return (
              <motion.div
                key={feat.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: index * 0.1 }}
                whileHover={{ y: -5 }}
                className="p-6 rounded-2xl border border-border bg-card shadow-sm hover:shadow-md transition-all flex flex-col justify-between group"
              >
                <div>
                  <div className={cn("h-12 w-12 rounded-xl flex items-center justify-center mb-6", feat.color)}>
                    <Icon className="h-6 w-6" />
                  </div>
                  <h3 className="text-lg font-bold mb-2 text-foreground group-hover:text-primary transition-colors">
                    {feat.title}
                  </h3>
                  <p className="text-muted-foreground text-sm leading-relaxed">
                    {feat.description}
                  </p>
                </div>
              </motion.div>
            );
          })}
        </div>
      </section>

      {/* How it Works */}
      <section className="py-20 md:py-28 bg-zinc-50 dark:bg-zinc-950/40 border-y border-border">
        <div className="max-w-7xl mx-auto px-6 md:px-12 w-full">
          <div className="text-center space-y-3 mb-16">
            <h2 className="text-3xl md:text-4xl font-extrabold tracking-tight">
              A 3-Step Journey to Carbon Neutrality
            </h2>
            <p className="text-muted-foreground max-w-lg mx-auto text-sm">
              We make lowering your digital footprints simple, gamified, and engaging.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {steps.map((st, index) => (
              <motion.div
                key={st.step}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: index * 0.15 }}
                className="space-y-4 p-6 rounded-2xl bg-background border border-border/80 relative"
              >
                <div className="text-4xl font-extrabold bg-gradient-to-r from-emerald-500 to-teal-400 bg-clip-text text-transparent">
                  {st.step}
                </div>
                <h3 className="text-lg font-bold text-foreground">{st.title}</h3>
                <p className="text-muted-foreground text-sm leading-relaxed">{st.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Footer Section */}
      <section className="py-20 md:py-24 text-center px-6 bg-gradient-to-b from-background to-zinc-900/10 dark:to-emerald-950/10">
        <div className="max-w-3xl mx-auto space-y-8">
          <h2 className="text-3xl md:text-5xl font-extrabold tracking-tight">
            Ready to reduce your bytes of carbon?
          </h2>
          <p className="text-muted-foreground max-w-lg mx-auto text-sm md:text-base">
            Join hundreds of digital citizens managing their streaming, cloud, and computing habits.
          </p>
          <Link href="/signup">
            <Button size="lg" className="bg-emerald-600 hover:bg-emerald-500 text-white font-bold px-8 py-6 rounded-2xl shadow-lg cursor-pointer">
              Get Started for Free
            </Button>
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="mt-auto border-t border-border py-8 px-6 md:px-12 flex flex-col md:flex-row items-center justify-between text-muted-foreground text-xs gap-4 bg-card/40">
        <div className="flex items-center gap-2">
          <span>🌿</span>
          <span className="font-semibold text-foreground">EcoByte</span>
          <span>© 2026. All rights reserved.</span>
        </div>
        <div className="flex gap-6">
          <Link href="/login" className="hover:text-foreground">
            Sign In
          </Link>
          <Link href="/signup" className="hover:text-foreground">
            Sign Up
          </Link>
          <a href="#" className="hover:text-foreground">
            Privacy Policy
          </a>
        </div>
      </footer>
    </div>
  );
}
